# Generated by Django 2.2.5 on 2019-09-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_owner'),
        ('pokers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poker',
            unique_together={('team', 'member')},
        ),
    ]
