# Generated by Django 2.2.7 on 2020-01-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('pokers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poker',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokers', to='teams.Member'),
        ),
        migrations.AddField(
            model_name='poker',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokers', to='teams.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='poker',
            unique_together={('team', 'member')},
        ),
    ]
