# Generated by Django 2.2.5 on 2019-09-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
    ]
