# Generated by Django 2.2.5 on 2019-09-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20190924_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='staffs',
            field=models.ManyToManyField(through='teams.Member', to='teams.Staff'),
        ),
    ]
