# Generated by Django 2.2.5 on 2019-09-21 03:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190920_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='invited_by',
        ),
        migrations.AlterField(
            model_name='member',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.Staff'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='checkin_hour',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='standup_hour',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teams.Organization'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='teams.Organization'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to=settings.AUTH_USER_MODEL),
        ),
    ]
