# Generated by Django 2.2.5 on 2019-09-30 08:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
