# Generated by Django 2.2.5 on 2019-09-24 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190924_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='checkin_day',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Friday'), (0, 'Monday'), (5, 'Saturday'), (6, 'Sunday'), (3, 'Thursday'), (1, 'Tuesday'), (2, 'Wednesday')], default=3, validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
