# Generated by Django 2.2.5 on 2019-09-23 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190921_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Checkin'), (1, 'Standup')], default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.Organization'),
        ),
    ]
