# Generated by Django 2.2.7 on 2020-01-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('meetings', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teams.Member'),
        ),
        migrations.AddField(
            model_name='standup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standups', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.Question'),
        ),
        migrations.AddField(
            model_name='response',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='meetings.Submission'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='teams.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('member', 'meeting_type', 'meeting_id')},
        ),
        migrations.AlterUniqueTogether(
            name='standup',
            unique_together={('team', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('question', 'submission')},
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('team', 'year', 'week')},
        ),
    ]
