# Generated by Django 2.2.5 on 2019-09-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupresponse',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Member'),
        ),
        migrations.AddField(
            model_name='standupresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Question'),
        ),
        migrations.AddField(
            model_name='standupresponse',
            name='standup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_responses', to='meetings.Standup'),
        ),
        migrations.AddField(
            model_name='standup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standups', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='checkinresponse',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to='meetings.Checkin'),
        ),
        migrations.AddField(
            model_name='checkinresponse',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Member'),
        ),
        migrations.AddField(
            model_name='checkinresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Question'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='teams.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='standupresponse',
            unique_together={('question', 'member', 'standup')},
        ),
        migrations.AlterUniqueTogether(
            name='standup',
            unique_together={('team', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='checkinresponse',
            unique_together={('question', 'member', 'checkin')},
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('team', 'year', 'week')},
        ),
    ]
