# Generated by Django 2.2.5 on 2019-09-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20190926_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Closed'), (1, 'Open')], default=1),
        ),
    ]
