# Generated by Django 2.2.5 on 2019-09-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_submission_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='teams.Member'),
        ),
    ]
