# Generated by Django 2.2.5 on 2019-09-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20190927_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='kind',
            new_name='status',
        ),
    ]
