# Generated by Django 2.2.5 on 2019-10-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20190930_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Closed'), (1, 'Open'), (2, 'Submitted')], default=1),
        ),
    ]
