# Generated by Django 2.2.7 on 2020-01-03 07:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('kind', models.PositiveSmallIntegerField(choices=[(3, 'Boolean'), (4, 'Choice'), (5, 'Multiple Choice'), (2, 'Numeric'), (1, 'Text')], default=1)),
                ('category', models.PositiveSmallIntegerField(choices=[(2, 'Checkin'), (1, 'Standup')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
