# Generated by Django 2.2.5 on 2019-09-24 03:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2047)])),
                ('week_of_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(52)])),
            ],
        ),
        migrations.CreateModel(
            name='CheckinResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to='checkins.Checkin')),
            ],
        ),
    ]
