# Generated by Django 2.2.5 on 2019-09-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkins', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinresponse',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to='teams.Member'),
        ),
        migrations.AddField(
            model_name='checkinresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to='teams.Question'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='teams.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='checkinresponse',
            unique_together={('question', 'member', 'checkin')},
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('team', 'year', 'week_of_year')},
        ),
    ]
