# Generated by Django 2.2.5 on 2019-09-21 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinquestion',
            old_name='mandatory',
            new_name='is_mandatory',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='checkinquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_questions', to='teams.Question'),
        ),
        migrations.AlterField(
            model_name='checkinquestion',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_questions', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='checkinresponse',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to='teams.Member'),
        ),
        migrations.AlterField(
            model_name='checkinresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_responses', to='teams.Question'),
        ),
    ]
