# Generated by Django 2.2.5 on 2019-09-24 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20190924_0719'),
        ('checkins', '0002_auto_20190924_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='week',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(53)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('team', 'year', 'week')},
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='week_of_year',
        ),
    ]
