# Generated by Django 2.2.5 on 2019-09-16 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_remove_team_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandupResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Member')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Question')),
            ],
            options={
                'unique_together': {('member', 'question')},
            },
        ),
        migrations.CreateModel(
            name='StandupQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandatory', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'unique_together': {('team', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Standup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'unique_together': {('team', 'date')},
            },
        ),
    ]
