# Generated by Django 2.2.5 on 2019-09-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standups', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupresponse',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_responses', to='teams.Member'),
        ),
        migrations.AddField(
            model_name='standupresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_responses', to='teams.Question'),
        ),
        migrations.AddField(
            model_name='standupresponse',
            name='standup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standup_responses', to='standups.Standup'),
        ),
        migrations.AddField(
            model_name='standup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standups', to='teams.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='standupresponse',
            unique_together={('question', 'member', 'standup')},
        ),
        migrations.AlterUniqueTogether(
            name='standup',
            unique_together={('team', 'date')},
        ),
    ]
